version: "3"
services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
      - 27018:27018
      - 27019:27019
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    ports:
      - 8085:8085
    links:
      - mongodb:mongo
    depends_on:
      - mongodb
    environment:
      VCAP_APP_PORT: 8085
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example